myapp/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('feedback/', views.feedback, name='feedback'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('service/', views.service, name='service'),
    
    
    #create task url here
    path('create-task/', views.create_task, name='create-task'),
    path('task-list/', views.task_list, name='task-list'),
    path('update-task/<int:id>/', views.update_task, name='update-task'),
    path('delete-task/<int:id>/', views.delete_task, name='delete-task'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    subject = models.CharField(max_length=255)
    message = models.TextField()

    def __str__(self):
        return self.name
    
    class Meta:
        # verbose_name = "Contact"
        # verbose_name_plural = "Contacts"
        pass


class Service(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.ImageField(upload_to='services/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title + " -----------> "+ f"{self.created_at}"
    
    class Meta:
        verbose_name = "Service"
        verbose_name_plural = "Services"
        
        
class Task(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField()
    status = models.BooleanField()
    
    def __str__(self):
        return self.title

myapp/forms.py
from django import forms


#create forms here
class FeedbackForm(forms.Form):
    name = forms.CharField()
    content = forms.CharField(widget=forms.Textarea)
    date = forms.DateField()

myapp/views.py
from django.shortcuts import render, redirect
from myapp.forms import *
from .models import *

# Create your views here.
def home(request):
    return render(request, 'index.html')


def contact(request):
    #body
    return render(request, 'contact.html')


def feedback(request):
    form = FeedbackForm()
    return render(request, 'feedback.html', {'form': form})


def portfolio(request):
    #body
    return render(request, 'about.html')


def service(request):
    #body
    return render(request, 'service.html')


def create_task(request):
    if request.method == "POST":
        title = request.POST.get('title')
        description = request.POST.get('description')
        status = request.POST.get('status', False)
        
        if status == "on":
            status = True
        else:
            status = False    
        Task.objects.create(title=title, description=description, status=status)
        return redirect('task-list')
      
    return render(request, 'task/create-task.html')


def task_list(request):
    tasks = Task.objects.all()
    return render(request, 'task/task-list.html', {'tasks': tasks})



#status field doesn't update properly
def update_task(request, id):
    task = Task.objects.get(id=id)
    if request.method == "POST":
        title = request.POST.get('title')
        description = request.POST.get('description')
        status = request.POST.get('status', False)
        if status == "on":
            status = True
        else:
            status = False
        Task.objects.update(title=title, description=description, status=status)
        return redirect('task-list')
    return render(request, 'task/update-task.html', {'task': task})


def delete_task(request, id):
    task = Task.objects.get(id=id)
    task.delete()
    return redirect('task-list')

myapp/templates/about.html
{% extends "xyz/base.html" %}



{% block content %}
    <h1>This is customizable about page.</h1>
{% endblock content %}
    

myapp/templates/contact.html
{% extends "xyz/base.html" %}



{% block content %}
    {% include 'sidebar.html' %}
    <h1>This is customizable contact page.</h1>
{% endblock content %}

myapp/templates/feedback.html
{% extends "xyz/base.html" %}



{% block content %}
    <h1>This is customizable feedback page.</h1>
    {{ name }}
{% endblock content %}
    

myapp/templates/index.html
{% extends "xyz/base.html" %}
{% load static %}


{% block content %}
    <h1>This is customize home page.</h1> 
{% endblock content %}

    

myapp/templates/service.html
{% extends "xyz/base.html" %}



{% block content %}
    <h1>This is customizable service page.</h1>
{% endblock content %}
    

myapp/templates/task/create-task.html
{% extends "xyz/base.html" %}



{% block content %}
    <section id="create-task my-5">
        <div class="container my-3">
            <div class="row justify-content-center">
                <div class="col-11 col-md-8 col-lg-5 p-3 shadow rounded-3 bg-white">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="form-group mb-3">
                          <label for="id_title" class="form-label">Title</label>
                          <input type="text" class="form-control" name="title" id="id_title" placeholder="Task title here ...">
                        </div>
                        <div class="form-group mb-3">
                          <label for="id_description" class="form-label">Description</label>
                          <textarea name="description" class="form-control" id="id_description" cols="30" rows="4" placeholder="Task description here ..."></textarea>
                        </div>
                        <div class="form-group mb-3">
                          <div class="form-check">
                            <input type="hidden" name="status" value="False">
                            <input class="form-check-input" type="checkbox" id="gridCheck" name="status">
                            <label class="form-check-label" for="gridCheck">
                              Is Completed?
                            </label>
                          </div>
                        </div>
                        <div class="col-12">
                          <button type="submit" class="btn btn-primary">Create Task</button>
                        </div>
                      </form>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

myapp/templates/task/task-list.html
{% extends "xyz/base.html" %}



{% block content %}
    <section id="create-task my-5">
        <div class="container my-3">
            <div class="row justify-content-center">
                <div class="col-11 col-md-10 col-lg-12 p-3 bg-white">
                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">#ID</th>
                            <th scope="col">Title</th>
                            <th scope="col">Description</th>
                            <th scope="col">Status</th>
                            <th scope="col">Actions</th>
                          </tr>
                        </thead>
                        <tbody>
                          {% for x in tasks %}
                          <tr>
                            <th scope="row">{{ x.id }}</th>
                            <td>{{ x.title }}</td>
                            <td>{{ x.description }}</td>
                            <td>{{ x.status }}</td>
                            <td>
                                <a href="/update-task/{{ x.id }}/" class="btn btn-info">Edit</a>
                                <a href="/delete-task/{{ x.id }}/" class="btn btn-danger">Delete</a>
                            </td>
                          </tr>
                          {% empty %}
                          <tr>
                            <th scope="row">Task is not available.</th>
                          </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

myapp/templates/task/update-task.html
{% extends "xyz/base.html" %}



{% block content %}
    <section id="create-task my-5">
        <div class="container my-3">
            <div class="row justify-content-center">
                <div class="col-11 col-md-8 col-lg-5 p-3 shadow rounded-3 bg-white">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="form-group mb-3">
                          <label for="id_title" class="form-label">Title</label>
                          <input type="text" class="form-control" name="title" id="id_title" value="{{ task.title }}" placeholder="Task title here ...">
                        </div>
                        <div class="form-group mb-3">
                          <label for="id_description" class="form-label">Description</label>
                          <textarea name="description" class="form-control" id="id_description" cols="30" rows="4" placeholder="Task description here ...">{{ task.description }}</textarea>
                        </div>
                        <div class="form-group mb-3">
                          <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="gridCheck" name="status" {% if task.status %}checked{% endif %}>
                            <label class="form-check-label" for="gridCheck">
                              Is Completed?
                            </label>
                          </div>
                        </div>
                        <div class="col-12">
                          <button type="submit" class="btn btn-primary">Create Task</button>
                        </div>
                      </form>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}